name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    permissions:
      contents: write # ⬅️ 'permissions'는 'update-readme' 아래에 두 칸 들여쓰기
    name: Update Readme with Waka Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: athul/waka-readme@v2 # 'uses'는 'steps' 아래에 두 칸 들여쓰기
        with:                     # ⬅️ 'with'는 'uses'와 같은 레벨에 있어야 합니다.
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: "true"
          SHOW_TIMEZONE: "true"
          SHOW_TOTAL: "true"
          SHOW_MASKED_TIME: "false"
          SHOW_LINES_OF_CODE: "false"
          SHOW_PROFILE_VIEWS: "false"
          SHOW_COMMIT: "true" # ⚠️ 기존 파일에 'SHOW_COMMIT'이 누락되어 있어서 추가했습니다.
          SHOW_DAYS_OF_WEEK: "true"
          SHOW_LANGUAGE: "true"
          SHOW_EDITORS: "false"
          SHOW_OS: "false"
